name: C++ Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install clang-format -y

      - name: Run clang-format to fix code
        run: |
          find . -regex '.*\.\(cpp\|h\)' -not -path "./build/*" | xargs clang-format -style=file -i

      - name: Show diff if any
        run: git diff --exit-code || echo "⚠️ Code was auto-formatted. Please commit the changes."
